import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import DefaultLayout from "../components/defaultLayout";
import ExportToExcelFile from '../components/exportToExcelFile'
import axios from "axios";

export const getStaticProps = async () => {
  const response = await axios.get(
    "https://jsonplaceholder.typicode.com/users"
  );
  return {
    props: { users: response?.data },
  };
};

export default function Home({ users }) {
  return (
    <DefaultLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
        <ExportToExcelFile />
          <h1 className={"title"}>Users List</h1>
          <div className={"d-flex"}>
            {users &&
              users.map((user) => {
                return (
                  <Link href={`/user/${user.id}`} key={user.id}>
                    <div className={"card"}>
                      <p>
                        Name: <span>{user.name}</span>
                      </p>
                      <p>Phone: <span>{user.phone}</span></p>
                    </div>
                  </Link>
                );
              })}
          </div>
        </main>

        {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </div>
    </DefaultLayout>
  );
}
